services:
  app:
    build:
      context: .
      args:
        - TURNSTILE_SITE_KEY=${TURNSTILE_SITE_KEY}
    ports:
      - "4321:4321"
    env_file:
      - .env
    environment:
      - AUTH_DRIZZLE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
